const gunActions = {
  TOGGLE_GUN_MODE: 'TOGGLE_GUN_MODE',
  ADD_GUN_IN_ANIMATION: 'ADD_GUN_IN_ANIMATION',
  REMOVE_GUN_IN_ANIMATION: 'REMOVE_GUN_IN_ANIMATION',
  ADD_GUN_OUT_ANIMATION: 'ADD_GUN_OUT_ANIMATION',
  REMOVE_GUN_OUT_ANIMATION: 'REMOVE_GUN_OUT_ANIMATION',
  GUN_TRIGGER: 'GUN_TRIGGER',
  GUN_TRIGGER_DONE: 'GUN_TRIGGER_DONE'
}

export default gunActions;